CREATE DATABASE SDCDB;

USE SDCDB;

CREATE TABLE IF NOT EXISTS product (
  id SERIAL PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  slogan VARCHAR(50),
  description VARCHAR(300),
  category VARCHAR(20) NOT NULL,
  default_price SMALLINT,
);

CREATE TABLE IF NOT EXISTS styles (
  id SERIAL PRIMARY KEY,
  productId INTEGER FOREIGN KEY REFERENCES product(id) NOT NULL,
  name VARCHAR(30) NOT NULL,
  sale_price DECIMAL,
  original_price DECIMAL NOT NULL,
  default_style SMALLINT,
);

CREATE TABLE IF NOT EXISTS skus (
  id SERIAL PRIMARY KEY,
  styleId INTEGER FOREIGN KEY REFERENCES styles(id) NOT NULL,
  size VARCHAR(10) NOT NULL,
  quantity SMALLINT,
);

CREATE TABLE IF NOT EXISTS cart (
  id SERIAL PRIMARY KEY,
  user_session SMALLINT NOT NULL,
  productId INTEGER FOREIGN KEY REFERENCES product(id),
  active SMALLINT NOT NULL,
);

CREATE TABLE IF NOT EXISTS related (
  id SERIAL PRIMARY KEY,
  current_product_id INTEGER FOREIGN KEY REFERENCES product(id) NOT NULL,
  related_product_id INTEGER FOREIGN KEY REFERENCES product(id) NOT NULL,
)

CREATE TABLE IF NOT EXISTS photos (
  id SERIAL PRIMARY KEY,
  styleId INTEGER FOREIGN KEY REFERENCES styles(id),
  url VARCHAR(2100),
  thumbnail_url VARCHAR(2100),
);

CREATE TABLE IF NOT EXISTS features (
  id SERIAL PRIMARY KEY,
  productId INTEGER FOREIGN KEY REFERENCES product(id) NOT NULL,
  feature VARCHAR(30),
  value VARCHAR(30),
);


